### ISSUE TITLE
改进报错机制？

### ISSUE THREAD

**Issue by IM1903** [fengberd/VACJOKE.NET#2]
当游戏不运行时启用Animated Clantag就会基于所选的动态间隔进行报错，如何改为不进行任何操作或自动退出？

另：能否使动态模式有更多自定义组合呢？感谢你的工作，祝你生活愉快。

**Comment by fengberd** [comment]
您可以考虑在2019.6.9后联系我: berd@rbq.email
实在是忙不过来 GitHub都是一个月看一次

**Comment by fengberd** [comment]
报错问题已解决, 请查看 [此处](https://github.com/fengberd/VACJOKE.NET/releases/tag/v1.0.2.1)
关于动态模式的自定义组合请给我一些例子
